version: "3.8"

services:
  app:
    build: .

    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: jdbc:postgresql://torrefactoradb:5432/postgres?sslmode=disable
      DATABASE_USERNAME: mi_usuario
      DATABASE_PASSWORD: mi_password

    depends_on:
      - torrefactoradb

  torrefactoradb:
    build: ./../database